name: cookie
description: Example showing how to set, read, update and remove a cookie in Jaguar.
# version: 1.0.0
# homepage: https://www.example.com
# author: teja <email@example.com>

environment:
  sdk: '>=2.0.0-dev.65 <3.0.0'

dependencies:
  jaguar: ^2.2.16

dev_dependencies:
  test: ^1.3.0
